Django side
pyDoodle2Web/pyDoodle2Web-WebInterface pull request #3
Opened 2020-03-24 11:04 UTC by uniyalabhishek

2020-03-25 20:26 UTC, AayushDongre requested changes

2020-03-25 20:26 UTC, AayushDongre commented on components/footer/footer.py
> +        self.name = 'Footer'
@uniyalabhishek  change 'Footer' to 'footer'

2020-03-25 20:26 UTC, AayushDongre commented on components/footer/footer.py
> +        with open(os.path.join(os.getcwd(), 'components', 'footer', 'template.html')) as f:
use os.path.realpath(__file__) instead of getcwd()...check other components

2020-03-25 20:26 UTC, AayushDongre commented on components/footer/template.html
> +
@uniyalabhishek template should only have the relevant tag(div, footer etc) not all the tags

2020-03-26 18:15 UTC, therexone requested changes
Fix the path of template.html, check other components to learn the syntax.

2020-03-26 19:41 UTC, therexone commented
Fixed in another PR.

2020-03-26 19:41 UTC, closed without merging